#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace Tutorial { class USequenceDirector_C; }

namespace HostGame { class USequenceDirector_C; }

namespace Ignition { class USequenceDirector_C; }

